name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check out the repo
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p DOCKER_PASSWORD
    - name: build the Docker image
      run: docker build . --file Dockerfile --tag imap::$(date +%s)
         
    - name: Docker Push
      run: docker push ${{ secrets.DOCKER_USERNAME }}/imap
